beam:
  energy: 71.6764
  vector: {azimuth: 90.0, polar_angle: 90.0}
  source_distance: .inf
detectors:
  detector_1:
    pixels:
      columns: 2048
      rows: 2048
      size: [0.2, 0.2]
    saturation_level: 14000.0
    transform:
      translation: [0.0, 0.0, -1000.0]
      tilt: [0.0, 0.0, 0.0]
oscillation_stage:
  chi: 0.0
  translation: [0.0, 0.0, 0.0]
