powder:
  eta_tol: 2.0
  fit_tth_tol: 0.05
  max_iter: 5
  int_cutoff: 0.0001
  conv_tol: 0.0001
  pk_type: 'pvoigt'
  bg_type: 'linear'
  use_robust_optimization: false
laue_auto_picker:
  npdiv: 2
  tth_tol: 5.0
  eta_tol: 5.0
  fit_peaks: true
  fit_tth_tol: 0.1
  min_peak_int: 1.0
  do_smoothing: true
  smoothing_sigma: 2.0
  use_blob_detection: true
  blob_threshold: 0.25
crystal:
  grain_id: 2
  inv_stretch: [1.0, 1.0, 1.0, 0.0, 0.0, 0.0]
  orientation: [0.0, 0.0, 0.0]
  position: [0.0, 0.0, 0.0]
