powder:
  tth_tol: 0.2
  eta_tol: 2.0
  fit_tth_tol: 0.05
  max_iter: 5
  int_cutoff: 0.0001
  conv_tol: 0.0001
  pk_type: 'pvoigt'
  use_robust_optimization: false
crystal:
  grain_id: 2
  inv_stretch: [1.0, 1.0, 1.0, 0.0, 0.0, 0.0]
  orientation: [0.0, 0.0, 0.0]
  position: [0.0, 0.0, 0.0]
