polar:
  pixel_size_tth: 0.05
  pixel_size_eta: 0.20
  tth_min: 1.0
  tth_max: 20.0
  eta_min: -180.0
  eta_max: 180.0
  apply_snip1d: false
  snip1d_algorithm: 0
  snip1d_width: 0.2
  snip1d_numiter: 2
cartesian:
  pixel_size: 0.5
  virtual_plane_distance: 1000.0
  plane_normal_rotate_x: 0.0
  plane_normal_rotate_y: 0.0
colormap:
  min: 0
show_detector_borders: true
apply_pixel_solid_angle_correction: false
apply_lorentz_polarization_correction: false
lorentz_polarization:
  f_hor: 1.0
  f_vert: 0.0
