package:
  name: hexrdgui
  version: {{ environ.get('GIT_DESCRIBE_TAG', environ['GIT_FULL_HASH'][:8]) }}

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  entry_points:
    - hexrdgui = hexrdgui.main:main

requirements:
  build:
    - python {{ python }}                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python {{ python }}
    - setuptools
    - setuptools_scm

  run:
    - python
    - fabio
    - hexrd=={{ hexrd_version }}
    - matplotlib-base
    - Pillow
    - pyhdf
    - pyside6
    # FIXME: the latest qt6-main isn't compatible with PySide6, so we are pinning
    # the version. Remove this pin when this is fixed.
    - qt6-main==6.6.0
    - pyyaml
    - silx-base

test:         # [build_platform == target_platform]
  imports:
    - hexrdgui

about:
  home: https://github.com/HEXRD/hexrdgui
  license: BSD
  license_family: BSD
  summary: "Qt6 PySide6 based HEXRD GUI"
