package:
  name: hexrdgui
  version: {{ environ.get('GIT_DESCRIBE_TAG', environ['GIT_FULL_HASH'][:8]) }}

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  entry_points:
    - hexrdgui = hexrd.ui.main:main

requirements:
  build:
    - python=3.10
    - setuptools
    - setuptools_scm

  run:
    - python
    - fabio
    - hexrd=={{ hexrd_version }}
    - matplotlib-base
    - Pillow
    - pyhdf
    - pyside6
    - pyyaml
    - silx-base

test:
  imports:
    - hexrd.ui

about:
  home: https://github.com/HEXRD/hexrdgui
  license: BSD
  license_family: BSD
  summary: "Qt6 PySide6 based HEXRD GUI"
